Moving some stuff around

diff --git a/.github/workflows/build-uid2-dev-ami.yaml b/.github/workflows/build-uid2-dev-ami.yaml
--- a/.github/workflows/build-uid2-dev-ami.yaml
+++ b/.github/workflows/build-uid2-dev-ami.yaml
@@ -1,5 +1,5 @@
-name: Build UID2 and EUID AMIs
-run-name: Build UID2 and EUID AMIs for Operator Release ${{ inputs.operator_release }} by @${{ github.actor }}
+name: Build UID2 and EUID Dev AMIs
+run-name: Build UID2 and EUID Dev AMIs
 on:
   push:
     branches:
@@ -47,7 +47,6 @@ jobs:
           cp ./scripts/aws/proxies.host.yaml                                                                        ${ARTIFACTS_OUTPUT_DIR}/
           cp ./scripts/aws/sockd.conf                                                                               ${ARTIFACTS_OUTPUT_DIR}/
           cp ./scripts/aws/uid2operator.service                                                                     ${ARTIFACTS_OUTPUT_DIR}/
-          cp ./scripts/aws/pipeline/$(cat ${{ steps.buildFolder.outputs.BUILD_FOLDER }}/identity_scope.txt)_VERSION ${ARTIFACTS_OUTPUT_DIR}/VERSION
           cp ./scripts/aws/syslog-ng/syslog-ng-server.conf                                                          ${ARTIFACTS_OUTPUT_DIR}/
           cp ./scripts/aws/syslog-ng/server_al_2023/ivykis-0.43-1.amzn2023.x86_64.rpm                               ${ARTIFACTS_OUTPUT_DIR}/
           cp ./scripts/aws/syslog-ng/server_al_2023/libnet-1.2-2.amzn2023.0.2.x86_64.rpm                            ${ARTIFACTS_OUTPUT_DIR}/
@@ -84,15 +83,15 @@ jobs:
         - name: Checkout repo
           uses: actions/checkout@v4
 
-        - name: Pre-cleanup
-          shell: bash
-          working-directory: ${{ github.workspace }}
-          run: |
-            echo "Cleaning up previous run"
-            sudo rm -rf * || true
-            docker stop $(docker ps -aq) || true
-            docker rm $(docker ps -aq) || true
-            docker rmi $(docker images -q) || true
+#        - name: Pre-cleanup
+#          shell: bash
+#          working-directory: ${{ github.workspace }}
+#          run: |
+#            echo "Cleaning up previous run"
+#            sudo rm -rf * || true
+#            docker stop $(docker ps -aq) || true
+#            docker rm $(docker ps -aq) || true
+#            docker rmi $(docker images -q) || true
 
         - name: Run amazonlinux Docker image
           shell: bash
@@ -109,7 +108,6 @@ jobs:
             cp ./scripts/aws/proxies.host.yaml                                                                        ${ARTIFACTS_OUTPUT_DIR}/
             cp ./scripts/aws/sockd.conf                                                                               ${ARTIFACTS_OUTPUT_DIR}/
             cp ./scripts/aws/uid2operator.service                                                                     ${ARTIFACTS_OUTPUT_DIR}/
-            cp ./scripts/aws/pipeline/$(cat ${{ steps.buildFolder.outputs.BUILD_FOLDER }}/identity_scope.txt)_VERSION ${ARTIFACTS_OUTPUT_DIR}/VERSION
             cp ./scripts/aws/syslog-ng/syslog-ng-server.conf                                                          ${ARTIFACTS_OUTPUT_DIR}/
             cp ./scripts/aws/syslog-ng/server_al_2023/ivykis-0.43-1.amzn2023.x86_64.rpm                               ${ARTIFACTS_OUTPUT_DIR}/
             cp ./scripts/aws/syslog-ng/server_al_2023/libnet-1.2-2.amzn2023.0.2.x86_64.rpm                            ${ARTIFACTS_OUTPUT_DIR}/
